# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myimg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mepic(object):
    def __init__(self,msg,pdp):
        self.msg=msg
        self.pdp=pdp
    def setupUi(self, Mine):
        Mine.setObjectName("Mine")
        Mine.resize(785, 449)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Mine)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 744, 622))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Mine)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setStyleSheet("border-radius: 10%;")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.setStyleSheet("background-color: #ecf0f1; color: #2f3640; border-radius: 10%;")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mssg = QtWidgets.QLabel(self.widget_2)
        self.mssg.setMinimumSize(QtCore.QSize(280, 280))
        self.mssg.setMaximumSize(QtCore.QSize(480, 360))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.mssg.setFont(font)
        self.mssg.setText("")
        self.mssg.setPixmap(QtGui.QPixmap(self.msg))
        self.mssg.setScaledContents(True)
        self.mssg.setAlignment(QtCore.Qt.AlignCenter)
        self.mssg.setWordWrap(True)
        self.mssg.setObjectName("mssg")
        self.horizontalLayout_3.addWidget(self.mssg)
        self.img = QtWidgets.QLabel(self.widget_2)
        self.img.setEnabled(True)
        self.img.setMinimumSize(QtCore.QSize(100, 100))
        self.img.setMaximumSize(QtCore.QSize(100, 100))
        self.img.setStyleSheet("border-radius : 50%;")
        self.img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap(self.pdp))
        self.img.setScaledContents(True)
        self.img.setWordWrap(False)
        self.img.setObjectName("img")
        self.horizontalLayout_3.addWidget(self.img)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Mine)
        QtCore.QMetaObject.connectSlotsByName(Mine)

    def retranslateUi(self, Mine):
        _translate = QtCore.QCoreApplication.translate
        Mine.setWindowTitle(_translate("Mine", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mine = QtWidgets.QWidget()
    ui = Ui_Mepic("imgs/jerry.jpg","imgs/tom.jpg")
    ui.setupUi(Mine)
    Mine.show()
    sys.exit(app.exec_())
