# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'online.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Online(object):
    def __init__(self,usn,pdp,O):
        self.pdp=pdp
        self.usn=usn
        self.O=O
    def setupUi(self, Online):
        Online.setObjectName("Online")
        Online.resize(400, 300)
        Online.setStyleSheet("background-color: #ecf0f1;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Online)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 251, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Online)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img.setEnabled(self.O)
        self.img.setMinimumSize(QtCore.QSize(50, 50))
        self.img.setMaximumSize(QtCore.QSize(70, 70))
        self.img.setStyleSheet("border-radius : 50%;")
        self.img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img.setText("")
        P=QtGui.QPixmap(self.pdp)
        self.img.setPixmap(P)
        self.img.setScaledContents(True)
        self.img.setWordWrap(False)
        self.img.setObjectName("img")
        self.horizontalLayout_2.addWidget(self.img)
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Pagella Math")
        font.setPointSize(20)
        font.setBold(True)
        self.name.setFont(font)
        self.name.setScaledContents(False)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setWordWrap(True)
        self.name.setStyleSheet("color : #2c3e50;")
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)

        self.retranslateUi(Online)
        QtCore.QMetaObject.connectSlotsByName(Online)

    def retranslateUi(self, Online):
        _translate = QtCore.QCoreApplication.translate
        Online.setWindowTitle(_translate("Online", "Form"))
        self.name.setText(_translate("Online", self.usn))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Online = QtWidgets.QWidget()
    ui = Ui_Online('SuS',"imgs/tom.jpg",True)
    ui.setupUi(Online)
    Online.show()
    sys.exit(app.exec_())
