# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'theirtxt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Their(object):
    def __init__(self,msg,usn,pdp):
        self.msg=msg
        self.usn=usn
        self.pdp=f'imgs/Avatars/Avatar{pdp}.png'
    def setupUi(self, Their):
        Their.setObjectName("Their")
        Their.resize(564, 600)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Their)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 260, 317, 130))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Their)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget_5.setStyleSheet("background-color: #dedede; \n"
"color: #2f3640; border-radius: 10%;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3.addWidget(self.widget_6)
        self.img_2 = QtWidgets.QLabel(self.widget_5)
        self.img_2.setEnabled(True)
        self.img_2.setMinimumSize(QtCore.QSize(100, 100))
        self.img_2.setMaximumSize(QtCore.QSize(100, 100))
        self.img_2.setStyleSheet("border-radius : 50%;")
        self.img_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_2.setText("")
        self.img_2.setPixmap(QtGui.QPixmap(self.pdp))
        self.img_2.setScaledContents(True)
        self.img_2.setWordWrap(False)
        self.img_2.setObjectName("img_2")
        self.verticalLayout_3.addWidget(self.img_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.USN = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.USN.setFont(font)
        self.USN.setStyleSheet("color:#3498db;")
        self.USN.setObjectName("USN")
        self.verticalLayout_2.addWidget(self.USN)
        self.mssg = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.mssg.setFont(font)
        self.mssg.setScaledContents(True)
        self.mssg.setAlignment(QtCore.Qt.AlignLeft)
        self.mssg.setWordWrap(True)
        self.mssg.setObjectName("mssg")
        self.verticalLayout_2.addWidget(self.mssg)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.widget_2 = QtWidgets.QWidget(self.widget_5)
        self.widget_2.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.widget_5)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)

        self.retranslateUi(Their)
        QtCore.QMetaObject.connectSlotsByName(Their)

    def retranslateUi(self, Their):
        _translate = QtCore.QCoreApplication.translate
        Their.setWindowTitle(_translate("Their", "Form"))
        self.USN.setText(_translate("Their", self.usn))
        self.mssg.setText(_translate("Their", self.msg))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Their = QtWidgets.QWidget()
    ui = Ui_Their("Holaaaaa.......!","USN here",'imgs/jerry.jpg')
    ui.setupUi(Their)
    Their.show()
    sys.exit(app.exec_())
